import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#022448',
        'primary-container': '#1e3a5f',
        'on-primary': '#ffffff',
        'on-primary-container': '#8aa4cf',
        'on-primary-fixed': '#001c3b',
        'on-primary-fixed-variant': '#2d486d',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#adc8f5',
        'inverse-primary': '#adc8f5',
        'secondary': '#555f70',
        'secondary-container': '#d6e0f4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5a6374',
        'secondary-fixed': '#d9e3f7',
        'secondary-fixed-dim': '#bdc7da',
        'on-secondary-fixed': '#121c2a',
        'on-secondary-fixed-variant': '#3e4757',
        'tertiary': '#341f00',
        'tertiary-container': '#503300',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#c69b5f',
        'tertiary-fixed': '#ffddb2',
        'tertiary-fixed-dim': '#edbf7f',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#60410c',
        'surface': '#faf9fc',
        'surface-dim': '#dad9dd',
        'surface-bright': '#faf9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f7',
        'surface-container': '#eeedf1',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e3e2e6',
        'surface-variant': '#e3e2e6',
        'surface-tint': '#455f87',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        'background': '#faf9fc',
        'on-background': '#1a1c1e',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
